name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: ./.github/workflows/my-pr-comment-trigger.yml
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_CLOUD_CREDENTIALS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
